# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [60]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [61]:
weather_df = pd.read_csv('Resources/weather_city_data.csv')

weather_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,mataura,-46.1927,168.8643,20.00,80,85,2.24,NZ,1614487863
1,hermanus,-34.4187,19.2345,21.11,80,79,5.36,ZA,1614487863
2,halifax,44.6453,-63.5724,5.00,100,100,9.77,CA,1614487806
3,yar-sale,66.8333,70.8333,-25.69,89,9,4.85,RU,1614487864
4,jamestown,42.0970,-79.2353,-1.11,95,1,1.59,US,1614487764
...,...,...,...,...,...,...,...,...,...
563,skibbereen,51.5500,-9.2667,2.00,93,75,1.54,IE,1614488038
564,marystown,47.1666,-55.1483,-3.77,94,34,4.86,CA,1614488039
565,kahului,20.8947,-156.4700,24.00,64,1,6.69,US,1614488039
566,zhangye,38.9342,100.4517,-2.26,58,100,2.26,CN,1614488039
567,zharkent,44.1628,80.0000,-1.38,45,15,4.22,KZ,1614488040

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [62]:
locations = weather_df[["Lat", "Lng"]]
weights = weather_df["Humidity"]

In [63]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=weights, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)

fig.add_layer(heat_layer)


fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [64]:
#Max Temp is metric units


ideal_weather_df = weather_df.loc[(weather_df['Max Temp'] < 30) & (weather_df['Max Temp'] > 18)& (weather_df['Wind Speed'] < 10)& (weather_df['Cloudiness'] == 0)]


# ideal_weather_df.reset_index(drop=True)

hotel_df = ideal_weather_df.dropna()

hotel_df.reset_index(drop=True)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,springbok,-29.6643,17.8865,18.28,43,0,1.54,ZA,1614487865
1,puerto escondido,15.8500,-97.0667,24.59,70,0,2.34,MX,1614487574
2,sao filipe,14.8961,-24.4956,19.43,75,0,5.48,CV,1614487867
3,saint-philippe,-21.3585,55.7679,29.00,61,0,8.23,RE,1614487875
4,namibe,-15.1961,12.1522,19.92,82,0,1.65,AO,1614487878
5,cape town,-33.9258,18.4232,21.11,77,0,1.54,ZA,1614487659
6,chuy,-33.6971,-53.4616,20.57,78,0,4.54,UY,1614487871
7,umm lajj,25.0213,37.2685,21.53,54,0,3.76,SA,1614487887
8,santa maria,-29.6842,-53.8069,19.32,78,0,3.87,BR,1614487899
9,ginir,7.1333,40.7000,18.38,39,0,2.46,ET,1614487637
10,emboscada,-25.1500,-57.3500,25.00,78,0,2.06,PY,1614487907
11,east london,-33.0153,27.9116,19.00,94,0,2.57,ZA,1614487908
12,tres de maio,-27.7733,-54.2400,22.22,81,0,0.89,BR,1614487722
13,wajir,1.7471,40.0573,25.00,78,0,1.03,KE,1614487925
14,sur,22.5667,59.5289,23.89,59,0,6.07,OM,1614487936
15,tacuarembo,-31.7333,-55.9833,18.01,88,0,4.01,UY,1614487939
16,bouca,6.5105,18.2733,18.83,35,0,0.59,CF,1614487940
17,aden,12.7794,45.0367,25.27,74,0,4.99,YE,1614487944
18,maldonado,-34.6667,-54.9167,21.00,88,0,5.14,UY,1614487962
19,paoua,7.2427,16.4406,19.68,30,0,1.82,CF,1614487965
20,saint-pierre,-21.3393,55.4781,29.00,61,0,8.23,RE,1614487976
21,acapulco,16.8634,-99.8901,23.55,76,0,1.30,MX,1614487979
22,taunggyi,20.7833,97.0333,26.76,18,0,2.12,MM,1614487981
23,camoapa,12.3839,-85.5116,19.26,89,0,5.96,NI,1614487987
24,qandala,11.4720,49.8728,26.14,54,0,1.94,SO,1614487827
25,moron,-34.6534,-58.6198,25.00,65,0,6.17,AR,1614488004
26,pokaran,26.9167,71.9167,26.70,15,0,1.47,IN,1614488004
27,banikoara,11.2985,2.4386,21.47,21,0,2.45,BJ,1614488007
28,kaiyuan,23.6977,103.3037,22.63,36,0,8.00,CN,1614488011
29,manaus,-3.1019,-60.0250,27.00,78,0,1.03,BR,1614487793
30,ormara,25.2088,64.6357,23.25,27,0,3.71,PK,1614488018
31,machali,-34.1833,-70.6667,19.30,41,0,0.81,CL,1614488024
32,pochutla,15.7432,-96.4661,23.89,92,0,1.73,MX,1614488027
33,mirpur khas,25.5251,69.0159,25.50,9,0,3.03,PK,1614488031
34,perth,-31.9333,115.8333,29.44,39,0,7.20,AU,1614487755

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [65]:
hotel_df['Hotel Name'] = ""

hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
7,springbok,-29.6643,17.8865,18.28,43,0,1.54,ZA,1614487865,
12,puerto escondido,15.8500,-97.0667,24.59,70,0,2.34,MX,1614487574,
14,sao filipe,14.8961,-24.4956,19.43,75,0,5.48,CV,1614487867,
39,saint-philippe,-21.3585,55.7679,29.00,61,0,8.23,RE,1614487875,
48,namibe,-15.1961,12.1522,19.92,82,0,1.65,AO,1614487878,
50,cape town,-33.9258,18.4232,21.11,77,0,1.54,ZA,1614487659,
66,chuy,-33.6971,-53.4616,20.57,78,0,4.54,UY,1614487871,
75,umm lajj,25.0213,37.2685,21.53,54,0,3.76,SA,1614487887,
111,santa maria,-29.6842,-53.8069,19.32,78,0,3.87,BR,1614487899,
127,ginir,7.1333,40.7000,18.38,39,0,2.46,ET,1614487637,
138,emboscada,-25.1500,-57.3500,25.00,78,0,2.06,PY,1614487907,
139,east london,-33.0153,27.9116,19.00,94,0,2.57,ZA,1614487908,
172,tres de maio,-27.7733,-54.2400,22.22,81,0,0.89,BR,1614487722,
196,wajir,1.7471,40.0573,25.00,78,0,1.03,KE,1614487925,
229,sur,22.5667,59.5289,23.89,59,0,6.07,OM,1614487936,
240,tacuarembo,-31.7333,-55.9833,18.01,88,0,4.01,UY,1614487939,
241,bouca,6.5105,18.2733,18.83,35,0,0.59,CF,1614487940,
257,aden,12.7794,45.0367,25.27,74,0,4.99,YE,1614487944,
307,maldonado,-34.6667,-54.9167,21.00,88,0,5.14,UY,1614487962,
318,paoua,7.2427,16.4406,19.68,30,0,1.82,CF,1614487965,
354,saint-pierre,-21.3393,55.4781,29.00,61,0,8.23,RE,1614487976,
364,acapulco,16.8634,-99.8901,23.55,76,0,1.30,MX,1614487979,
371,taunggyi,20.7833,97.0333,26.76,18,0,2.12,MM,1614487981,
387,camoapa,12.3839,-85.5116,19.26,89,0,5.96,NI,1614487987,
419,qandala,11.4720,49.8728,26.14,54,0,1.94,SO,1614487827,
443,moron,-34.6534,-58.6198,25.00,65,0,6.17,AR,1614488004,
444,pokaran,26.9167,71.9167,26.70,15,0,1.47,IN,1614488004,
457,banikoara,11.2985,2.4386,21.47,21,0,2.45,BJ,1614488007,
470,kaiyuan,23.6977,103.3037,22.63,36,0,8.00,CN,1614488011,
474,manaus,-3.1019,-60.0250,27.00,78,0,1.03,BR,1614487793,
493,ormara,25.2088,64.6357,23.25,27,0,3.71,PK,1614488018,
515,machali,-34.1833,-70.6667,19.30,41,0,0.81,CL,1614488024,
524,pochutla,15.7432,-96.4661,23.89,92,0,1.73,MX,1614488027,
537,mirpur khas,25.5251,69.0159,25.50,9,0,3.03,PK,1614488031,
546,perth,-31.9333,115.8333,29.44,39,0,7.20,AU,1614487755,

In [66]:
params = {
    "radius": 50000,
    "types": "lodging",
    "key": g_key
}


for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

  
    params["location"] = f"{lat},{lng}"

    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

  
    name_address = requests.get(base_url, params=params)
    



    name_address = name_address.json()
   
    try:
        x = hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
        print(x)

    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
hotel_df.head()

Biesjesfontein B&B
Aldea del Bazar Hotel and Spa
Tortuga B&B
HÃ´tel L'Ecrin
Hotel Chik Chik Namibe
Southern Sun Waterfront Cape Town
La Casa de las Boyas
Moon light Furnished Units
Hotel Morotin
Sura Dare Village
La MisiÃ³n Hotel Boutique
Tu Casa
SÃªnior Parque Hotel
Al-bustan Hotel And Restaurant.
Sur Plaza Hotel
Complejo San Fructuoso
Missing field/result... skipping.
Sama Emirate Hotel
Punta del Este Resort & Spa
Quartier Paoua Elien
HÃ´tel Le Cilaos
HS Hotsson Smart Acapulco
True Treasure Hotel
Ethos Inn
Missing field/result... skipping.
Hotel MorÃ³n
Luxury Resort near Jodhpur, Desert Dunes Camp Tent in Jaisalmer | Thar Oasis Resort and Camp
HÃ´tel de l'UCom CVPC
Phoenix Hotel
Manaus HotÃ©is Millennium
Crystal Beach and Camping Resort Ormara
Hotel Mar Andino
La Isla Huatulco
Hotel Al-Fajar
Beatty Lodge

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
7,springbok,-29.6643,17.8865,18.28,43,0,1.54,ZA,1614487865,Biesjesfontein B&B
12,puerto escondido,15.8500,-97.0667,24.59,70,0,2.34,MX,1614487574,Aldea del Bazar Hotel and Spa
14,sao filipe,14.8961,-24.4956,19.43,75,0,5.48,CV,1614487867,Tortuga B&B
39,saint-philippe,-21.3585,55.7679,29.00,61,0,8.23,RE,1614487875,HÃ´tel L'Ecrin
48,namibe,-15.1961,12.1522,19.92,82,0,1.65,AO,1614487878,Hotel Chik Chik Namibe

In [67]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [68]:
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))